name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Install packages
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    - name: Build page
      uses: borales/actions-yarn@v4
      with:
        cmd: build
      env:
        CI: ""
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
          branch: gh-pages
          folder: build

